### ISSUE TITLE
this can complete only by start an croutine and new waitforsecends()

### ISSUE THREAD

**Issue by zyxia** [akbiggs/UnityTimer#4]

**Comment by akbiggs** [comment]
If you mean that WaitForSeconds() does the same thing as the library, the repository README describes a few reasons why this library is different: https://github.com/akbiggs/UnityTimer#motivation

**Comment by zyxia** [comment]
class Test: MonoBehaviour
{
private IEnumerator ttttt(float per,Action TestFunc)
{ 
         yield return new WaitForSeconds(per);
        TestFunc();
        this.startCroutine(this.ttttt(per,TestFunc));
}
 

void Start() {
   this.startCroutine(this.ttttt(2f, () => Debug.Log("You won't see this text if you press X.")));
}

void Update() {
   if (Input.GetKeyDown(KeyCode.X)) {
       this.stopCroutine("ttttt");
   }
}
}


what's the different

**Comment by akbiggs** [comment]
1. Set Time.timeScale = 0f and your coroutine won't run. You can pass "useRealTime: true" to Timer.Register to have timers that ignore the time scale.

2. The Timer object returned from Timer.Register has nice functions for evaluating the progress made and cancelling the timer without needing to hardcode the enumerator name.

3. I found writing the coroutine approach repeatedly annoying and required more boilerplate / lines to remember than I wanted, so I wrote this library for my own convenience and figured other people might be interested.

**Comment by zyxia** [comment]
ok
